baseurl = "/"
languageCode = "en-uk"
title = "Dyfan Jones Brain Dump Centre"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "dyfanjones"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/DyfanJones"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/dyfan-jones-a8261799/"

[params]
    description = "A website to brain dump ideas"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

